first_name = input("Please type in your first name: ")
last_name = input("Please type in your last name: ")
email = input("Please type in your email adress: ")
phone_number = input("Please type in your phone number: ")
job_title = input("Please type in your job title: ")
id = input("Please type in your ID number: ")
print()
print("The ID Card is")
print("-----------------------------------------")
print(last_name.upper() + "," + first_name)
print(job_title.title())
print("ID: " + id)
print()
print(email.lower())
print(phone_number)
print("-----------------------------------------")
